### ISSUE TITLE
xml-stylesheet kullanımında ilk xml etiketini eklemiyor.

### ISSUE THREAD

**Issue by 3ddark** [uparlayan/FluentXML#3]
Dosya oluştururken bu `<?xml-stylesheet type="text/xsl" href="general.xslt"?>`
satırı eklersem **AsString** fonksiyonu içindeki `<?xml version="1.0" encoding="UTF-8"?>` satırını eklemiyor.

Örnek kullandığım kod burada
` XML :=
New.Version(1.0).Encoding(TEncoding.UTF8).NameSpace('').Add('?xml-stylesheet type="text/xsl" href="general.xslt"?', True).Add('InvoiceLine',....`

Ben kendi kodumda AsString fonksiyonu içindeki Pos ile aramaya boşluk version şeklinde baktırdım. Sorunsuz çalıştı. Ayrıca line break atmak gerekiyor.
if (Pos( '<?xml version',_Source, 1) <= 0) then begin
satırını

**Comment by uparlayan** [comment]
TFluentXML nesnesine StyleSheet özelliği eklendi ve probşem düzeltildi.
