### ISSUE TITLE
Etiket başlama ve bitişler

### ISSUE THREAD

**Issue by 3ddark** [uparlayan/FluentXML#4]
E-Fatura XML dosyasında olduğu gibi bir çıktı alamadım.
Siyah arka plan olan resim E-Fatura resmi sitesinde verdiği XML dosyaya ait görsel
![Screenshot_2](https://user-images.githubusercontent.com/5977787/59695387-d4370700-91f2-11e9-979b-089d8dbebcaa.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/5977787/59695420-e31db980-91f2-11e9-884f-e2ab98af3f13.jpg)
Beyaz arka plan olan resim programın çıktısı

**Comment by uparlayan** [comment]
Muhtemelen kurgunuzda bir yanlışlık olabilir. Bununla birlikte kod örneğinizi görmeden yorum yapmak çok zor. Bu problem ile ilgili proje grubuna bir demo örneği eklendi. Örneği inceleyerek probleminizi çözebilirsiniz.
